# Generated by Django 5.1.4 on 2025-06-18 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Код сброса пароля',
                'verbose_name_plural': 'Коды сброса пароля',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Номер телефона')),
                ('post_user', models.CharField(choices=[('improver', 'Практикант'), ('trainee', 'Стажер'), ('specialist', 'Специалист'), ('expert', 'Эксперт'), ('manager', 'Менеджер'), ('unapproved', 'Неутвержденный')], default='unapproved', max_length=20, null=True, verbose_name='Должность')),
                ('avatar', models.ImageField(default='static/img/default_avatar.jpg', upload_to='avatars/', verbose_name='Аватар')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('pending_type', models.CharField(choices=[('improver', 'Практикант'), ('trainee', 'Стажер'), ('specialist', 'Специалист'), ('expert', 'Эксперт'), ('manager', 'Менеджер'), ('unapproved', 'Неутвержденный')], max_length=20, null=True, verbose_name='Ожидающий тип')),
                ('user_type_confirmed', models.BooleanField(default=False, verbose_name='Тип подтвержден')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки кода')),
                ('big_stavka', models.FloatField(default=0, verbose_name='Ставка')),
                ('prize', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PrizeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма премии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_history', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История премий',
                'verbose_name_plural': 'История премий',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_post', models.CharField(max_length=255, verbose_name='Запрашиваемая должность')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на повышение',
                'verbose_name_plural': 'Запросы на повышение',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_type', models.CharField(choices=[('task', 'Task Timer'), ('shift', 'Shift Timer')], default='task', max_length=10, verbose_name='Тип таймера')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager2.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись времени',
                'verbose_name_plural': 'Записи времени',
            },
        ),
    ]
