# Generated by Django 5.1.4 on 2025-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='timer_type',
            field=models.CharField(choices=[('task', 'Task Timer'), ('shift', 'Shift Timer')], default='task', max_length=10),
        ),
    ]
