# Generated by Django 5.2.1 on 2025-05-28 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0005_alter_photo_options_alter_photofile_options_and_more'),
        ('users', '0003_timeentry_timer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Код сброса пароля', 'verbose_name_plural': 'Коды сброса пароля'},
        ),
        migrations.AlterModelOptions(
            name='prizehistory',
            options={'ordering': ['-date'], 'verbose_name': 'История премий', 'verbose_name_plural': 'История премий'},
        ),
        migrations.AlterModelOptions(
            name='promotionrequest',
            options={'verbose_name': 'Запрос на повышение', 'verbose_name_plural': 'Запросы на повышение'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Запись времени', 'verbose_name_plural': 'Записи времени'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='static/img/default_avatar.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='big_stavka',
            field=models.FloatField(default=0, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки кода'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pending_type',
            field=models.CharField(choices=[('improver', 'Практикант'), ('trainee', 'Стажер'), ('specialist', 'Специалист'), ('expert', 'Эксперт'), ('manager', 'Менеджер'), ('unapproved', 'Неутвержденный')], max_length=20, null=True, verbose_name='Ожидающий тип'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_user',
            field=models.CharField(choices=[('improver', 'Практикант'), ('trainee', 'Стажер'), ('specialist', 'Специалист'), ('expert', 'Эксперт'), ('manager', 'Менеджер'), ('unapproved', 'Неутвержденный')], default='unapproved', max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type_confirmed',
            field=models.BooleanField(default=False, verbose_name='Тип подтвержден'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='requested_post',
            field=models.CharField(max_length=255, verbose_name='Запрашиваемая должность'),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager2.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='timer_type',
            field=models.CharField(choices=[('task', 'Task Timer'), ('shift', 'Shift Timer')], default='task', max_length=10, verbose_name='Тип таймера'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
