# Generated by Django 5.1.4 on 2025-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('image_name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Название изображения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('estimated_time', models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое время')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='photo_files/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл фотографии',
                'verbose_name_plural': 'Файлы фотографий',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('layout', models.CharField(default='default_value', max_length=100, verbose_name='Макет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('submitted', 'Отправлена на проверку'), ('reviewed', 'Проверена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('quality_confirmed', models.BooleanField(default=True, verbose_name='Качество подтверждено')),
                ('is_submitted_for_review', models.BooleanField(default=False, verbose_name='Отправлено на проверку')),
                ('contractor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подрядчик')),
                ('time_spent', models.FloatField(default=0.0, verbose_name='Затраченное время')),
                ('earnings', models.FloatField(default=0.0, verbose_name='Заработок')),
                ('max_assigned_users', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество пользователей')),
                ('stopping', models.BooleanField(default=False, verbose_name='Остановлено')),
                ('is_rated', models.BooleanField(default=False, verbose_name='Оценено')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Оценка')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('is_notification_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
            ],
            options={
                'verbose_name': 'Оценка задачи',
                'verbose_name_plural': 'Оценки задач',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный шаблон')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Учет времени менеджера',
                'verbose_name_plural': 'Учет времени менеджеров',
                'ordering': ['-start_time'],
            },
        ),
    ]
