# Generated by Django 5.1.4 on 2025-06-18 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный менеджер'),
        ),
        migrations.AddField(
            model_name='photofile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='manager2.photo', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначено на'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные пользователи'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by_users',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Завершено пользователями'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_muser', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='manager2.photo', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_by',
            field=models.ManyToManyField(related_name='submitted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено пользователями'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_by_users_for_review',
            field=models.ManyToManyField(blank=True, related_name='tasks_submitted_for_review', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено на проверку пользователями'),
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manager2.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviews', to='manager2.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='manager2.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='timemanger',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timemanger_set', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterUniqueTogether(
            name='taskreview',
            unique_together={('task', 'user')},
        ),
    ]
