# Generated by Django 5.1.4 on 2025-03-05 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_by_users_for_review',
            field=models.ManyToManyField(blank=True, related_name='tasks_submitted_for_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timemanger',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timemanger_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
