# Generated by Django 5.2.1 on 2025-05-28 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0004_alter_task_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='photofile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл фотографии', 'verbose_name_plural': 'Файлы фотографий'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Обзор', 'verbose_name_plural': 'Обзоры'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskreview',
            options={'ordering': ['-reviewed_at'], 'verbose_name': 'Оценка задачи', 'verbose_name_plural': 'Оценки задач'},
        ),
        migrations.AlterModelOptions(
            name='timemanger',
            options={'ordering': ['-start_time'], 'verbose_name': 'Учет времени менеджера', 'verbose_name_plural': 'Учет времени менеджеров'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='task',
            name='selected',
        ),
        migrations.AddField(
            model_name='task',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('submitted', 'Отправлена на проверку'), ('reviewed', 'Проверена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='is_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный менеджер'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='estimated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое время'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_name',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='file',
            field=models.FileField(upload_to='photo_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='manager2.photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manager2.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначено на'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные пользователи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by_users',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Завершено пользователями'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_muser', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='earnings',
            field=models.FloatField(default=0.0, verbose_name='Заработок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_rated',
            field=models.BooleanField(default=False, verbose_name='Оценено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_submitted_for_review',
            field=models.BooleanField(default=False, verbose_name='Отправлено на проверку'),
        ),
        migrations.AlterField(
            model_name='task',
            name='layout',
            field=models.CharField(default='default_value', max_length=100, verbose_name='Макет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_assigned_users',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество пользователей'),
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='manager2.photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quality_confirmed',
            field=models.BooleanField(default=True, verbose_name='Качество подтверждено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stopping',
            field=models.BooleanField(default=False, verbose_name='Остановлено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted_by',
            field=models.ManyToManyField(related_name='submitted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено пользователями'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted_by_users_for_review',
            field=models.ManyToManyField(blank=True, related_name='tasks_submitted_for_review', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено на проверку пользователями'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.FloatField(default=0.0, verbose_name='Затраченное время'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviews', to='manager2.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='timemanger',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timemanger',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timemanger_set', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='timemanger',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный шаблон')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='manager2.tasktemplate', verbose_name='Шаблон задачи'),
        ),
    ]
