# Generated by Django 5.1.4 on 2025-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0006_task_requirements_tasktemplate_max_assigned_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='max_assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_assigned_users',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество пользователей'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='requirements',
            field=models.TextField(verbose_name='Требования'),
        ),
    ]
