# Generated by Django 5.2.1 on 2025-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0007_remove_tasktemplate_max_assigned_users_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
